### ISSUE TITLE
window is not defined for next.js

### ISSUE THREAD

**Issue by santoshgistto** [thanhtunguet/grapesjs-react#13]
Throwing error for nextjs window is not defined

**Comment by thanhtunguet** [comment]
Hello @santoshgistto,
Look at the last line of this file: [GEditor.js](https://github.com/thanhtunguet/grapesjs-react/blob/master/src/components/GEditor.js):

```javascript
window.grapesjs = window.GrapesJS = GrapesJS;
```

I bound the grapesjs variable to window to make it accessible in global scope. I think it is the reason why you got this issue.
This may because of the bundling configuration of your project, the next.js framework or something similar. It does not resolve the window identifier.
Anyway, I still do not have solution. Can you help me for this?

**Comment by GabrielCheung128** [comment]
I think you could use `dynamic import` with configuration on ssr to be false. This is caused by that Nextjs is rendering the page in server, while there's no `window` object in server side.

**Comment by thanhtunguet** [comment]
Hi all,
this package is just a wrapper of GrapesJS for React on the client side so that it only works well on the client side. If you want to use it for server side rendering, you may need a deeper configuration than what I did.

**Comment by asharimh97** [comment]
I solve `window is not defined` in Next JS by dynamically import the lib. But somehow another error comes up. It said that...

```
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'separate;' is not a valid attribute name.
    at HTMLTableElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:12:3232)
    at w (http://localhost:8080/_next/static/chunks/1.js:12:1237)
    at m.each (http://localhost:8080/_next/static/chunks/1.js:12:4141)
    at m.attr (http://localhost:8080/_next/static/chunks/1.js:12:3197)
    at m.attr (http://localhost:8080/_next/static/chunks/1.js:12:3280)
    at r.updateAttributes (http://localhost:8080/_next/static/chunks/1.js:11:66376)
    at renderAttributes (http://localhost:8080/_next/static/chunks/1.js:11:67356)
    at render (http://localhost:8080/_next/static/chunks/1.js:11:67427)
    at r.addToCollection (http://localhost:8080/_next/static/chunks/1.js:12:62420)
    at http://localhost:8080/_next/static/chunks/1.js:12:62913
    at Function.m.each.m.forEach (http://localhost:8080/_next/static/chunks/1.js:11:2857)
    at r.each (http://localhost:8080/_next/static/chunks/1.js:11:19401)
    at render (http://localhost:8080/_next/static/chunks/1.js:12:62886)
    at renderChildren (http://localhost:8080/_next/static/chunks/1.js:11:67190)
    at render (http://localhost:8080/_next/static/chunks/1.js:11:67481)
    at Object.render (http://localhost:8080/_next/static/chunks/1.js:21:82000)
    at renderBody (http://localhost:8080/_next/static/chunks/1.js:21:175597)
    at I (http://localhost:8080/_next/static/chunks/1.js:11:8856)
    at HTMLIFrameElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:11:9060)
    at HTMLIFrameElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:11:2170)
```

I don't know why, but when I try it on create-react-app application, it just works fine. Any idea?

**Comment by thanhtunguet** [comment]
> I solve `window is not defined` in Next JS by dynamically import the lib. But somehow another error comes up. It said that...
> 
> ```
> Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'separate;' is not a valid attribute name.
>     at HTMLTableElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:12:3232)
>     at w (http://localhost:8080/_next/static/chunks/1.js:12:1237)
>     at m.each (http://localhost:8080/_next/static/chunks/1.js:12:4141)
>     at m.attr (http://localhost:8080/_next/static/chunks/1.js:12:3197)
>     at m.attr (http://localhost:8080/_next/static/chunks/1.js:12:3280)
>     at r.updateAttributes (http://localhost:8080/_next/static/chunks/1.js:11:66376)
>     at renderAttributes (http://localhost:8080/_next/static/chunks/1.js:11:67356)
>     at render (http://localhost:8080/_next/static/chunks/1.js:11:67427)
>     at r.addToCollection (http://localhost:8080/_next/static/chunks/1.js:12:62420)
>     at http://localhost:8080/_next/static/chunks/1.js:12:62913
>     at Function.m.each.m.forEach (http://localhost:8080/_next/static/chunks/1.js:11:2857)
>     at r.each (http://localhost:8080/_next/static/chunks/1.js:11:19401)
>     at render (http://localhost:8080/_next/static/chunks/1.js:12:62886)
>     at renderChildren (http://localhost:8080/_next/static/chunks/1.js:11:67190)
>     at render (http://localhost:8080/_next/static/chunks/1.js:11:67481)
>     at Object.render (http://localhost:8080/_next/static/chunks/1.js:21:82000)
>     at renderBody (http://localhost:8080/_next/static/chunks/1.js:21:175597)
>     at I (http://localhost:8080/_next/static/chunks/1.js:11:8856)
>     at HTMLIFrameElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:11:9060)
>     at HTMLIFrameElement.<anonymous> (http://localhost:8080/_next/static/chunks/1.js:11:2170)
> ```
> 
> I don't know why, but when I try it on create-react-app application, it just works fine. Any idea?

Please leave your webpack configuration here to check and if it is possible, configure webpack with `devtool: "site-map"` to find out where the error occurs in the code.
